### ISSUE TITLE
Running cron job inside the container?

### ISSUE THREAD

**Issue by rosshettel** [diginc/docker-pi-hole#107]
Just digging around the set up of the container and was curious why the `docker-pi-hole.cron` jobs couldn't be run from within the container itself? If there's no technical reason this won't work/isn't desired, would you be open to a PR adding this functionality?

**Comment by diginc** [comment]
Adding more processes is another step away from what #15 aims to accomplish, a single processes per container with multiple containers.  The single process style is more in line with docker's recommended best practices which I prefer over the monolithic VM style you see sometimes. #15 is starting to look more and more like a pipe dream however so maybe I should break down and add supervisord and cron :D

**Comment by rosshettel** [comment]
Ah gotcha. Yeah, I have a slightly opinionated view on that - I feel like the spirit of the suggestion is a role per container - like app, database, memcahe, etc. Not so necessarily down to minute processes like cron, ssh, etc. Especially when dockerizing apps - I feel like cron jobs and such should just be a part of it, makes it simpler. But I haven't looked into any of the docker swarm features yet, might be easier

**Comment by diginc** [comment]
I try to do [single concern containers](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/each-container-should-have-only-one-concern), for the sake of users' ease of access I combined web & dns (pi-hole isn't pi-hole without both IMO).  I think back when I first made this container their crontab wasn't even a default part of pi-hole's install.  Updating ad lists is pretty important so I agree adding cron in the container would be good for users.

It just makes me feel weird running a duplicate cron instance inside a container when I have a perfectly good one on my docker host.  The same applies to syslog and logrotate, if you ask me to add those too you'll get a hard no because [unlike the cron issue](https://github.com/docker/docker/issues/23880) or scheduled tasks](http://janetkuo.github.io/docs/user-guide/scheduled-jobs/), logs are [pretty well taken care of by docker](https://docs.docker.com/engine/admin/logging/overview/) with the right set of argument flags.

**Comment by alexleekt** [comment]
👍 for the request.
My QNAP NAS does not have a proper cron. :(

**Comment by RichieB2B** [comment]
It seems silly to me to run a `docker exec pihole_container_name pihole updateGravity` on the host, especially with the verbose output it produces. IMHO updates should be handled inside the container.

**Comment by diginc** [comment]
Been working on this but felt dirty adding more services with out a proper supervisor.  so I'm refactoring the whole container base layer and adding [s6-overlay](https://github.com/just-containers/s6-overlay) to be the new init/supervisor.  It'll be nice when done, just taking a while to wrap my head around and keep everything functional :)

**Comment by RichieB2B** [comment]
Sounds good. In case it helps: https://hub.docker.com/r/lsiobase/alpine/ already includes S6 overlay.

**Comment by diginc** [comment]
Quick update: I am still working on this, I'm trying to get all the regression tests to pass.  S6 is mostly working, just a few quirks with the service restarts.

**Comment by diginc** [comment]
Dev tags now include #123 changes and are available for testing https://hub.docker.com/r/diginc/pi-hole/tags/ - I haven't added any crontabs or tested yet however - that might make it in before going to production tags though.

**Comment by diginc** [comment]
Should be working in new release

**Comment by mr-bolle** [comment]
Hi, now i switch to the debian Container, then the flus of the log file works with the crontab.

The Container i start with follow command:
``` 
docker run -d --name pihole -p 53:53/tcp -p 53:53/udp -p 800:80 -e TZ=Europe/Berlin -e ServerIP=192.168.178.29 -e DNS1=192.168.178.15 -e DNS2=213.73.91.35 -e WEBPASSWORD='secure' --restart=always diginc/pi-hole:debian | or diginc/pi-hole:alpine
```

````
date;docker exec -it pihole-debian date
So 24. Dez 08:55:53 CET 2017
Sun Dec 24 08:55:53 CET 2017
````
I noticed another behavior in the alpine container, and i see some differences with the timezone into it.
```
date;docker exec -it pihole-alpine date
So 24. Dez 08:54:03 CET 2017
Sun Dec 24 07:54:03 GMT 2017
```
We wish you a happy and peaceful Christmas  and all the best for 2018!
