### ISSUE TITLE
As of 2.13.1 new DNS error

### ISSUE THREAD

**Issue by JoeStratton** [diginc/docker-pi-hole#113]
Hi, This container has been working great, after updating to the latest I receive the following error that doesnt allow the container to start:

dnsmasq: missing parameter at line 42 of /etc/dnsmasq.d/01-pihole.conf

More specifically:
mounting \\\"/var/log/pihole.log\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/90c579ffeef24643f4814ce7a36c54a32cd17dfd0c39026ffa29f848a1aa2d33\\\" at \\\"/var/lib/docker/btrfs/subvolumes/90c579ffeef24643f4814ce7a36c54a32cd17dfd0c39026ffa29f848a1aa2d33/var/log/pihole.log\\\" caused \\\"not a directory\\\"\""

I have always had the same path mapping here (the default) for the log file.

Any ideas?

**Comment by diginc** [comment]
There is a new setupVar required in the new release.  Same thing bit me
when I reused my old volume.   I think PIHOLE_INTERFACE=eth0 is what I
added to fix.

**Comment by JoeStratton** [comment]
Interesting, that took away the DNS error, which i thought was related to the 2nd error but apparently not.

This still remains:
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:53: mounting \\\"/var/log/pihole.log\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/95e7b2facee5c22be81ea39fd3d44aafdee8221853b25bf285a66ffbdcbdea08\\\" at \\\"/var/lib/docker/btrfs/subvolumes/95e7b2facee5c22be81ea39fd3d44aafdee8221853b25bf285a66ffbdcbdea08/var/log/pihole.log\\\" caused \\\"not a directory\\\"\""

**Comment by DL6ER** [comment]
`PIHOLE_INTERFACE=eth0` should be automatically added with `v2.13.1`. It might have been left out only on `v2.13`

**Comment by JoeStratton** [comment]
I also tried manually deleting and recreating /var/log/pihole.log but the error persists

**Comment by middleagedman** [comment]
Same here.. Debugging now.
Here's the commit reference.  Trying different run combinations, as just adding PIHOLE_INTERFACE to run cmd didn't work.. 
https://github.com/pi-hole/pi-hole/commit/051f4633501cb0dccdd0e03db06f86ea53256110

**Comment by middleagedman** [comment]
Bingo.. add this env var to your run parameters

  -e DNSMASQ_LISTENING="all" \

**Comment by diginc** [comment]
@middleagedman I added some notes to the README about that environment variable.   INTERFACE is prefered if you want single interface listening or you are using a non `--net=host` pi-hole.

**Comment by middleagedman** [comment]
Ok.. I don't know if it's optional though.. I couldn't get it to work with just standard settings.

**Comment by JoeStratton** [comment]
So as stated above the interface variable solved part 1. Any idea on the new path error or would you like a new issue for it? 
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:53: mounting \\\"/var/log/pihole.log\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/2b56fd64b141b322da13ae3c359bef71c347d27a87770a47734ee9bddf5ee663\\\" at \\\"/var/lib/docker/btrfs/subvolumes/2b56fd64b141b322da13ae3c359bef71c347d27a87770a47734ee9bddf5ee663/var/log/pihole.log\\\" caused \\\"not a directory\\\"\""
-

**Comment by diginc** [comment]
Joe, have you tried removing the container and volumes associated with it
completely and starting fresh?  Seems like a docker volume error.

If that doesn't work please post your docker run command.

On Sat, Mar 4, 2017, 9:53 PM middleagedman <notifications@github.com> wrote:

Ok.. I don't know if it's optional though.. I couldn't get it to work with
just standard settings.

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/diginc/docker-pi-hole/issues/113#issuecomment-284197512>,
or mute the thread

**Comment by JoeStratton** [comment]
I thought it was a docker volume issue as well, but the volumes did not change between upgrades. To test this, I deleted every volume in my config (except for etc/localtime) and the error persisted. I then also attempted to manually create the directories, which also gave me the error.

I am on unRaid but here is the config:

![pihole](https://cloud.githubusercontent.com/assets/6180439/23588339/760e0df6-0179-11e7-83bf-acc2634e9c56.PNG)

**Comment by diginc** [comment]
Have you tried a test run with no volumes?

The 'not a directory' error makes me think possibly you have a directory on
your host side that you're volume mapping the pihole.log to.  I.e. this
could be a directory instead of a file :
/var/lib/docker/btrfs/subvolumes/2b56fd64b141b322da13ae3c359bef71c347d27a87770a47734ee9bddf5ee663/var/log/pihole.log

Docker has a issue with assuming all mounts are directories and auto
creating directories on the host if a file doesn't exist they already.
Check all volumes are of the same file/directory type inside and outside
the container.
