### ISSUE TITLE
Use Alpine for ARM instead of Debian

### ISSUE THREAD

**Issue by rgsilva** [diginc/docker-pi-hole#116]
Hi,

I was wondering about the possibility of using an ARM port of Alpine instead of Debian for the `arm` tag. I've been playing with this in the last hours mostly for fun, but also because `tini` won't load on a RPi 1 (but will start just fine on a RPi 2). I think it might be related to their build: it might require at least an ARMv7, and the RPi 1 is an ARMv6. I didn't really went that far on checking it, all I saw is that `tini` wasn't starting on my RPi 1 with a segfault.

Anyway, just for the sake of it, I've trying using one of the ARM ports available for Alpine, `hypriot/rpi-alpine`. Since Alpine has its own `tini` build, the image wouldn't have to rely on downloading it externally. I've patched the necessary parts of the Dockerfile and started a container and it seems to work just fine. I didn't do an extensive test though.

The only small issue I've found so far is that PHP was built without IPv6 support, so that gives a warning in the admin console. Other than that, everything seems to be functional.

Anyway, my question is if you guys have thought about using an ARM port of Alpine instead of Debian for ARM (of even having support for both), or if maybe you're interested in this patch? :)

Cheers!

**Comment by diginc** [comment]
Without manually building the image on a RBPi 1 / armv6 I'm not sure it is possible to create the image.  
This sacrifices one of my image's top requirements: being fully automated.  The docker store/hub 'automated' seal of approval is something I and many others use as a sign of trust, since source code is auditable.

Both tini and the new init+supervisor system I'm looking at, s6-overlay, only seem to offer ARMHF (armv7) compatible cross compiled binaries.  So my goal of keeping an identical underlying init system/scripts would have to go away too.  

Right now my automated arm build runs on to of resin.io's qemu cross compiler binary+script setup, again there maybe a armhf only requirement for that stack.  RE:Alpine on my current automated ARM build, I know for sure alpine musl libc had issues with the qemu binaries resin added to make cross compiling work, even on armhf.

You can bring your own node to docker cloud (where my automated build runs) but the script they say to run to install their agent says say in the source (https://get.cloud.docker.com/) that it is x86 only at the moment.  Maybe someday though....

Feel free to fork and maintain your own docker file and I'd be willing to forward people onto your repository through a link in the README.

**Comment by rgsilva** [comment]
Unfortunately I'm not nearly familiar enough with Docker (and your stack, to be honest) to understand the issue, so I don't have the necessary skills to help you in most of that. :-( but I do understand the fact that being automated is a really big deal, and breaking it wouldn't be worth it.

Regarding the armhf build, it seems that you can, in theory, build armhf code for armv6, but it's somewhat painful. Debian's armhf is armv7 + some extensions, so I'm not sure how tricky would it be (and if it's worth it, to be honest). Still, tini's build would have to be changed, not yours. Ironically the alpine's ARM port I'm using does have tini on it, and it seems to work. I'll have to check how they're building that port eventually and I might contact them regarding this to see if there's anything that could be done (I don't think so). Or even an armel build, who knows.

I also looked up the new init system you mentioned, s6-overlay, and besides it being really interesting (bookmarked for future projects!), it seems that their armhf build might work on armv6, but I'll have to do an extensive test on it later. I extracted it and ran a few binaries (not nearly a good test, I know) and it seems to work. If you end up migrating from tini to s6-overlay, I might as well simply try to run it straight away and see what happens - might work.

I guess for now I'll stick with a local image based on your alpine for x86, but with the modifications to make it work on a RPi1. I'll try to keep it stable, and if it works fine, I might as well publish it as a fork, or at least build a script to download your image and patch it for RPi 1, so I don't have to do it manually every now and then.

Once I get more comfortable around the whole Docker environment (I've been playing with it only for a few weeks, still a noob :-)), I'll check everything out again and see how it goes from there.

Thanks nevertheless! Cheers!

**Comment by diginc** [comment]
Not sure if github pinged you because I linked/mentioned this issue from a comment in #177 @rgsilva so I thought I'd ping you direct.  

As mentioned in the [referenced comment](https://github.com/diginc/docker-pi-hole/issues/177#issuecomment-350567632) there maybe some hope automating an ARMv6 / RPi1 build using the armel tag of https://hub.docker.com/r/multiarch/debian-debootstrap/tags - will have to experiment and find out at some point.
