### ISSUE TITLE
Setting override at starting

### ISSUE THREAD

**Issue by Herve-M** [diginc/docker-pi-hole#117]
Hello,

I just noticed that at every start, the `setupVars.conf` is overridden by the default one. 

How to:
- docker run -v /etc/pihole/:/etc/pihole/ ...
- Make some change in the settings
- docker stop name
- docker start name 

I think a test must be done on the file, before overriding it. 

Herve-M

**Comment by diginc** [comment]
which key value setupVar setting are you concerned about persisting?  I try to make all the critical ones environment variables passed in by docker run so that volumes aren't required when destroying and re-creating the container.  I'm also using the pi-hole upstream bash functions for manipulating the setupVars...so that might be where it is blown away and written fresh every time.  I'll need to confirm this but I don't have a lot of my own logic for setupVars anymore.

**Comment by Herve-M** [comment]
Most of them yes, but for the moment I need the "Interface listening behavior" as my current setup can't mount the tun interface.. 

Edit: my bad, didn't get that `DNSMASQ_LISTENING` was what I looked for :/

**Comment by diginc** [comment]
Cool :)

related to #114
