### ISSUE TITLE
Update to 3.0 FTL integration

### ISSUE THREAD

**Issue by mukimov** [diginc/docker-pi-hole#122]
After upgrade to latest [pihole 3.0 ](https://github.com/pi-hole/pi-hole/releases/tag/v3.0) Pihole is not working anymore. It says that FTL is not active on admin page.

**Comment by Mattyfaz** [comment]
On the hub.docker page it says: 

> If you try to use pihole's built in updater it is not guaranteed to work; it almost assuredly won't work for alpine but debian may.

So I imagine we might have to wait for this to be updated, hopefully not long...

**Comment by diginc** [comment]
>So I imagine we might have to wait for this to be updated

Indeed - I'm working on it.  You should stay pinned to the old version and ignore the update popups for now.  

Until an upgrade is fully done and tested please don't try to upgrade the docker pi-hole version.  Debian image has a better chance of upgrading but upgrading the container is an experimental feature and not recommended (since the update disappears if you destroy and up from scratch)

**Comment by mukimov** [comment]
Normally people should not run `pihole updatePihole` as adviced in `docker-pi-hole.cron` file, it is better to comment this line out or warn people about breaking changes in future.

**Comment by diginc** [comment]
#123 PR will contain the upgrade along with s6 init system

**Comment by mvillarejo** [comment]
Looking forward seeing the new version on arm!
