### ISSUE TITLE
Undocumented environment variable used for ipv6

### ISSUE THREAD

**Issue by Rickkwa** [diginc/docker-pi-hole#129]
So you set `ServerIP` to be the external ipv4 address of your server. If you want to enable ipv6, you also need to set `ServerIPv6` to the ipv6 address of your server.

**Comment by diginc** [comment]
I'll have a pull request out soon that makes the container start script better accommodate #126's docker run command and documenting in the README.  The run command change is already in the [dev readme](https://github.com/diginc/docker-pi-hole/blob/dev/README.md) and I have a branch with documentation.

When I ran @middleagedman command for IPv6_LOOKUP : `IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')"`

I usually get 'kernel' so that set me on the path of adding validation to the input in the docker startup script...but it also begs the question, is that command right?

**Comment by diginc** [comment]
more info:


```
$ set -x ; IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')" ; set +x
++ ip -6 route get 2001:4860:4860::8888
++ awk '{ print $10; exit }'
+ IPv6_LOOKUP=kernel
+ set +x

$ ip -6 route get 2001:4860:4860::8888
unreachable 2001:4860:4860::8888 from :: dev lo  table unspec  proto kernel  src fe80::d250:99ff:fe86:9077  metric 4294967295  error -101 pref medium
```

**Comment by Rickkwa** [comment]
Uh, I think this topic is going over my head. My original intent was just to notify you that the table in the `Environment Variables` section of the README is missing a row to explain `ServerIPv6` variable.

**Comment by diginc** [comment]
I was sharing the additional info for @middleagedman - documenting it means it's ready for prime time and I don't think it is quite yet after testing it my self.

Either we need to not pass in IPv6 when the `ip route` command fails or validate after it is passed in and discard it.  I'm trying to implement the 2nd option.  I would push what I had to a branch but tests aren't passing and I dislike pushing broken tests.

**Comment by middleagedman** [comment]
So all that command does is query google.com's 8.8.8.8 dns (via ip6) and get it to return your ipv6 address.  If it says "unreachable", then it's possible your router or isp is not forwarding your ipv6 requests.  However, it still returns the ipv6 address of your machine, which is then used in the ipv6 display in the administrative settings

i.e. ifconfig -a returns on my machine
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.3  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::1540:7758:19df:61e4  prefixlen 64  scopeid 0x20<link>
        ether 00:1a:4d:59:4d:ca  txqueuelen 1000  (Ethernet)
        RX packets 20889795  bytes 10960032137 (10.2 GiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 20224284  bytes 12111091617 (11.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Then a simple command to return your ipv6 address is below

ip -6 route get 2001:4860:4860::8888
unreachable 2001:4860:4860::8888 from :: dev lo proto kernel src fe80::1540:7758:19df:61e4 metric 4294967295 error -101 pref medium

I was just trying to recreate what you are doing with the ipv4 command
IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')

Same principal.   You could just run this command, but then you would have to guess the name of the users nic interface (i.e. mine is enp5s0 instead of eth0).  There may be another file to grab that from..

ip addr show dev enp5s0 | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d'

**Comment by middleagedman** [comment]
PS - once I enabled ipv6 on my gateway router and configured my asus to do "tunnel 6rd".. It could do a proper route check to google, i.e.

└──╼ ip -6 route get 2001:4860:4860::8888
2001:4860:4860::8888 from :: via fe80::2e4d:54ff:fe00:7270 dev enp5s0 src 2602:304:cd37:7a40:86ba:59ab:b338:8479 metric 202 mtu 1480 pref medium

Of course.. most people will never do this but hey, if it's not too much work passing in the address (in this case I think its the 2602: address  .. fe80: is the link-local address.. i.e. 192.168

**Comment by diginc** [comment]
#130 covers documenting and validating potential errors in always passing in the output of `ip -6 route get` to ServerIPv6
