### ISSUE TITLE
Wally3k Block page support

### ISSUE THREAD

**Issue by titeishon** [diginc/docker-pi-hole#141]
Hi,

I'm trying to install Wally3k's block page to the debian container. I think it'd really help making pi-hole a family-proof service because they'd be able to whitelist any false positive from the browser.
https://github.com/WaLLy3K/Pi-hole-Block-Page 
I know the container isn't designed to support it natively, but I was hoping someone already figured it out and could give me some pointers. 

Cheers! and thanks for this awesome container!

**Comment by diginc** [comment]
Did you run into issues just entering into the debian container and running the steps?

`docker run -it pihole bash` will drop you to a prompt where you can try running the setup.

Alpine/latest tag will assuredly not work since it is NGINX.  It could be made to work if you change the 404 page configuration based off a quick glance at the instructions @WaLLy3K provides

**Comment by titeishon** [comment]
yes, I did run it on the debian container console, I usually make a bash script and just run it. 
The only error I get from the steps is that the force-reload command is not available. I usually just change it to restart. 

After restarting I I try a couple of sites but I still get the same block page. I did try to clear the cache and use a different browser with no avail.

**Comment by diginc** [comment]
I'll try it my self tonight and if I see any obvious problems/fixes reply back soon.

**Comment by titeishon** [comment]
did you try it? is it feasible?

cheers!

**Comment by diginc** [comment]
I did run into issues with the services restarting due to s6, I probably could have restarted the entire container as an alternative to just the service lighttpd restart, but instead I chased the s6 restart bug more since that has been on my radar since I upgraded and is a more general bug that should be addressed.

**Comment by titeishon** [comment]
they seem to be integrating the block page to the v3.3 release
https://github.com/pi-hole/pi-hole/pull/1416

so I guess you can close this "issue". 

Cheers!
