### ISSUE TITLE
Restarting the docker image overwrites the files in /etc/pihole

### ISSUE THREAD

**Issue by ax42** [diginc/docker-pi-hole#148]
I am using a volume mount in order to keep settings.  When I `docker stop pihole` and then `docker restart pihole` the setupVars.conf file and local.list files on the host are reset back to defaults.  The mount is working (I can edit local.list while the image is running, restart the dnsmasq in the image, and the changes are reflected).  The admin password is also reset to a new random value.

The query log survives the restart just fine.

Expected behaviour: config changes are kept across docker stop / restart.

**Comment by diginc** [comment]
The [environment variables](https://github.com/diginc/docker-pi-hole/blob/master/README.md#environment-variables) can be used to preserve the web password and other things.  What other setting is changing between restarts?

**Comment by ax42** [comment]
DNS Servers revert back to the google ones and the local.list file are the ones I've seen.

**Comment by diginc** [comment]
Do you set `-e DNS1` and `-e DNS2` in your docker run command?  Environment variables take precedence over volumes so there is no GUI configuration required.

**Comment by ax42** [comment]
I don't.  I am using only the script as it is describe in the docs.

I appreciate the fact that settings can be passed via environment variables, however:

1. The whole point of volume mounting the config files was (I thought) to make configs persistent.  That's what I had in mind when I described my expected behaviour above.
1. I don't see how environment variables help me with keeping `local.list` persistent

**Comment by Mcat12** [comment]
The container is supposed to be configured via env variables. The configs such as black and white lists are saved via volume mounting. `local.list` is an autogenerated file, using only the IP address and hostname of the Pi-hole as variables. You should not be modifying it, as it is overwritten on every gravity run.

**Comment by ax42** [comment]
Thanks for that info -- so if I want to add local hosts to the pi-hole DNS (e.g. by querying my DHCP leases with https://github.com/ax42/unifi-to-hosts-mapping ), what would be the best way to do this?

**Comment by Mcat12** [comment]
Add them to `/etc/hosts`

**Comment by diginc** [comment]
sounds like ax42 got it figured out but for anyone else in the future and completeness sake, you cannot directly edit /etc/hosts because docker fully manages it and makes it read only.  run time flags must be used to edit it:

https://docs.docker.com/engine/reference/run/#managing-etchosts

**Comment by Pmoshbr** [comment]
Any solutinon for this issue? I need to edit de local.list file, and I can't.
I have a range of static IP hardwares from my automation network, and I want to put all of then at my local.list file. 

Ex:
192.168.0.10 compressor_01
192.168.0.11 compressor_02
..... etc

And my DHCP range starts at 192.168.0.100

**Comment by mfigrs** [comment]
> sounds like ax42 got it figured out but for anyone else in the future and completeness sake, you cannot directly edit /etc/hosts because docker fully manages it and makes it read only. 

Not exactly. I've mapped the hosts file to local volume and was able to successfully edit it via `sudo vi hosts`. After restarting the pihole container it picked up host names - for both ipv4 and ipv6.

**Comment by diginc** [comment]
> Not exactly. I've mapped the hosts file to local volume and was able to successfully edit it via `sudo vi hosts`. After restarting the pihole container it picked up host names - for both ipv4 and ipv6.

I recently tested the same manual editing and found it worked to my surprise. I think /etc/hosts became managed+read write instead of read only since docker's early days.  This might open up some fun tricks we can pull.

**Comment by d-ognyanoff** [comment]
On RaspberryPi with Libreelec and Docker add-on. 

I solved this by adding the desired changes /storage/.config/hosts.conf:

192.168.xx.100    mylaptop
192.168.xx.102    second-laptop

which then gets written to **/etc/hosts** file of the libreelec (this is to have /etc/hosts persistent after restart in the LibreElec)

When I start the pihole container with:

`docker run -d \
--name pihole \
--cap-add NET_ADMIN \
-p 53:53/tcp \
-p 53:53/udp \
-p 80:80 \
-e DNS1=127.0.0.1 \
-e DNS2=1.1.1.1 \
-v /etc/localtime:/etc/localtime \
-v /storage/.config/pihole/:/etc/pihole \
-v /storage/.config/pihole/dnsmasq.d/:/etc/dnsmasq.d \
-v /storage/.config/pihole/html/:/var/www/html/html/ \

**-v /etc/hosts:/etc/hosts \**

-h $(cat /etc/hostname) \
-e ServerIP=$(ip route get 127.0.0.1 | awk '{ print $NF; exit }') \
-e WEBPASSWORD=password \
--restart=unless-stopped \
pihole/pihole:latest`


The pihole container start with the /etc/hosts mirrored from the /etc/hosts on the LibreElec. And after restart pihole's /etc/hosts is persistent. 

Interesting and highly satisfying is that if you change the entries on the host the Docker container is mirroring the file and you don't have to restart the container in order to get /etc/hosts updated.
