### ISSUE TITLE
Support Custom SSL configuration

### ISSUE THREAD

**Issue by kenperkins** [diginc/docker-pi-hole#162]
I've been able to hack the native install of PiHole to use SSL for the admin web interface. I'm wondering if that's something that could be enabled through docker and volumes with env variables to configure it.

**Comment by diginc** [comment]
I'm a big fan of not re-implementing X into every Y product where avoidable.  Molecularity over specialization if you will.  Reverse proxies are great for SSL since they front end any number of web application with whatever sort of webserver configuration you want, including SSL.

My go to in the docker world is always jwilder/nginx-proxy which does support SSL: https://github.com/jwilder/nginx-proxy#ssl-backends - it should be possible to get this working without any modifications to my container.  

I'd encourage a /admin/ SSL rule but be weary of trying to force SSL on the ad paths or you'll most likely get lots of mismatched SSL domain errors.

**Comment by kenperkins** [comment]
I'm certainly not against using `jwilder/nginx-proxy` although they don't appear to have an arm image which does get in my way at this point. Not excited about building my own image to solve that. Thanks.
