### ISSUE TITLE
Include LDAP Module for Ngnix

### ISSUE THREAD

**Issue by dbec** [diginc/docker-pi-hole#26]
I'd like to restrict access to the Admin page, using LDAP (AD) rather than local passwords. Would you consider adding "nginx-auth-ldap"? 

Thanks,
Daniel

**Comment by diginc** [comment]
I think ldap auth at the webserver level is going off the beaten track a bit too far to have it be an official feature in the docker-pi-hole.   It'd be a fun technical challenge but time doesn't really allow for me to take this on right now.  If you're curious about pursuing this more on your own here are some pointers:

My normal go to suggestion of using jwilder to be a wrapper around your real docker services doesn't really work here because I also did not see ldap in that image...jwidler's container could be rebuilt with ldap (swapping FROM nginx:1.9.15 with something like the @felixbuenemann nginx-ldap image's dockerfile) in it and then ANY docker service could have ldap auth dropped in front of it easily.

Swapping out the alpine nginx package with a different base image is a possibility but I didn't see an ideal alpine+nginx+ldap image which is regularly built.  This image has the right idea, but it doesn't pull from the upstream nginx fork regularly and re-build at similar intervals: https://hub.docker.com/r/felixbuenemann/nginx-ldap/

The ideal solution I can think of doesn't exist as of yet: I'd love if there was something for nginx like the docker php image that one-command-rebuilds from source with added extensions enabled through helper scripts.

One other thing that came to mind is maybe the pi-hole/pi-hole python rewrite is going to have some authentication and could eventually have an optional LDAP adapter right in the code.

**Comment by dbec** [comment]
Understood -- thanks for the suggestions. We can close this out.

**Comment by felixbuenemann** [comment]
@dbec I'm not actively using that image and I can't quite remember what I built it for, might've been for a private docker registry. You could try out the current version or copy the Dockerfile and edit it to suit your needs.
