### ISSUE TITLE
workaround for docker NAT with udp issue

### ISSUE THREAD

**Issue by oliverkurth** [diginc/docker-pi-hole#78]
I just installed the container on my Pi. I am using it together with an OpenVPN container, my goal was to connect to the VPN with my phone, and use pi-hole for blocking ads. It didn't work at first, although I had dnsmasq running in a container before, which worked fine: host names were not resolved when using the eth0 address of the Pi as the DNS server, but did work when I used the docker interface address of the pi-hole container. It took me some time until I remembered this issue (which I solved already for the old dnsmasq container, but forgot): https://github.com/docker/docker/issues/11998 . The workaround is to specify the IP address for the -p options, eg:

`docker run --rm -p 192.168.0.2:53:53/tcp -p 192.168.0.2:53:53/udp -p 192.168.0.2:80:80 --cap-add=NET_ADMIN -e ServerIP=192.168.0.2 --name pihole diginc/pi-hole:arm`

It may only be necessary for the udp port (I could use port 80 before the workaround).

This is probably worth noting in the instructions.

**Comment by diginc** [comment]
Interesting, I think I remember running into something like this too, containers going to the outside network and back in can be a little flaky it seems.  I think I'll make a 'Known issues section' & leave this issue open until that docker issue 11998 gets resolved.

Did you try linking your VPN container to the pihole container and using the hostname?  

I know sometimes you can't do DNS names for DNS servers, so you may require a custom startup/runtime script to write the translated hostname-> IP address to the openVPN config too.

My tests use a 2nd docker container to query the pihole one and it seems to work fine since it is going over internal docker networking.

**Comment by diginc** [comment]
Let me know if linking helped or not.  One thing I realized after writing about linking: --link is deprecated now and docker compose creates a unique network per compose project, auto linking everything in that docker network.
