### ISSUE TITLE
Request? redirect ad addresses to hostname?

### ISSUE THREAD

**Issue by tonyklawrence** [diginc/docker-pi-hole#88]
Sorry for this obtuse feature request, let me elaborate.

I am running this image inside docker on my Synology NAS.  It it working great (many thanks) however, the IP address that is returned for ads to be blocked is the IP of my Synology, therefore showing the Synology response from port 80.

I am able to reverse proxy the Synology NAS port 80 to the docker container running pi-hole however this is hostname based.

My request (maybe this should be to the authors of pi-hole?) is that instead of returning the value of ServerIP environment variable to pull ads from it would be great if I could re-direct them to a different hostname which would be the name used in the reverse proxy to get the data from pi-hole container.

I hope this makes some sense?

**Comment by diginc** [comment]
> My request (maybe this should be to the authors of pi-hole?) is that instead of returning the value of ServerIP environment variable to pull ads from it would be great if I could re-direct them to a different hostname which would be the name used in the reverse proxy to get the data from pi-hole container.

What pi-hole returns is DNS, which is IP based only.  Hostnames returned just won't mesh in the pi-hole ad blocking model since they don't have any logic (redirects like you suggested) ran against them until your browser hits the webserver.  The webserver of the IP it hits is what determine if it gets pi-hole or something else.

In my reverse proxy examples I make sure the pi-hole is the default virtual host.  virtual hosts determine what hostname goes to what service behind the reverse proxy (pi-hole or synology in your case).  There is always a default virtual host which is used when a browser connects to your webserver using a domain that you don't have defined in your configs (e.g. an ad domain for pihole).

It sounds like your default virtual host is synology instead of the docker and you might just need to flip them around in order of your config.

I just checked & it looks like synology is running apache so that confirms you just need pihole's virtualhost entry first in your configs (before synology's).  http://stackoverflow.com/questions/5427379/apache-default-virtualhost#5427520

**Comment by tonyklawrence** [comment]
Thanks, that's very clear on how it works, I was just hoping there was an easy way :-)

I'm very new to Synology but I understand that latest NAS OS (DSM 6.0) runs nginx which allows the reverse proxy setup, however, the default site (unmatched) goes the the admin page.  The UI will not allow me to change the wildcard for port 80 - this is what I would like to send to the pi-hole container.

I guess I will need to manually change the config on the box rather than relying on the admin UI.

Thanks for the reply and the docker alpine image!
If  I figure this out I'll update this issue if it's still possible to do so.

**Comment by diginc** [comment]
@tonyklawrence did changing vhost order fix your synology reverse proxy?  

Could you post an example for @buurman who was having trouble with his reverse proxy?

**Comment by tonyklawrence** [comment]
Sorry, I've not been able to get this to work.
For me pi-hole is working fine and blocking ads, it's just that the bad pages are redirected to the Synology 404 page which is better than the adverts.

The problem with the Synology is that it autogenerates the nginx conf from some json files.  I've tried to get the json file correct with a forward of port 80 but so far I have not managed it.

**Comment by tonyklawrence** [comment]
Ok, I've had a little more time to play with this.  The trick is to move the default Synology DSM port away from 80 which will then allow you to reverse proxy this.

The file on DSM 6.0 (update 9) is: /usr/syno/share/nginx/WWWService.mustache 
If you change the values 80 to something else then next time the web server restarts the Synology is listening on the new port.

This then allows you to add a reverse proxy via the control panel to forward all requests to any host (*) on port 80 to your pihole docker port 8080.

So far this is working ok for me, I plan to post about this with more detail which I'll come back and link to.

caveat: the reverse proxy ui does not allow you to choose port 80 as source, so you can set any port you want and then manually edit the file afterwards: /usr/syno/etc/www/ReverseProxy.json

**Comment by MattPark** [comment]
@tonyklawrence I'm sure you agree this is probably not the best solution. a) will break on updates b) assumes that you want to have pi-hole as default. Maybe multi-addressing (aliasing) the NIC with 2 ips could work.

**Comment by tonyklawrence** [comment]
@MattPark absolutely, I'd closed the issue and have now changed how I run it locally.  I've installed 'Web Station' so that I have a a web site served on port 80 (DSM is running on different port configured using the UI) and this way 404 pages are returned by default for all advert requests.  This seems to be working well for me.  This way there are no manual configuration changes and will survive updates.  I'm new to Synology so didn't initially know about 'Web Station' and what it offered.
