### ISSUE TITLE
Time Sync

### ISSUE THREAD

**Issue by Findarato** [diginc/docker-pi-hole#98]
It would be nice to allow for syncing of the time inside of the docker container with that of the host. Either through NTP or at least setting of the timezone.

**Comment by diginc** [comment]
Hi, there is a trick to doing this in docker so every container doesn't have to implement NTP.  I detailed the solution using your `docker run` command here:

https://github.com/diginc/docker-pi-hole/issues/74#issuecomment-265470383

Since you're the dns person to ask maybe I'll add it to the readme too :) pint #97
